// Player-paid level changes retain the foreign infrastructure's ownership and rights.
import assert from 'node:assert/strict';
import { flatGame, station } from './stationlib';
import { planRelevel, commitRelevel } from '../src/game/trackops';
import { serialize, deserialize } from '../src/game/save';
const g=flatGame(256);g.addAICompany({startMoney:30e6});g.aiEnabled=false;
const owner=g.ais[0].companyId, st=station(g,128,128,Math.PI/2,12,2,owner)!;
assert(st?.rail);
const tracks=[...st.rail.edges], ownerMoney=g.company(owner).economy.money;
let quote=planRelevel(g,tracks,'elevated',0);
assert(quote.ok,quote.error);assert(quote.cost>0);
const paid=g.economy.money;assert.equal(commitRelevel(g,quote),null);
assert.equal(st.owner,owner);assert.equal(st.rail.level,'elevated');
assert(tracks.every(id=>g.world.net.edges.get(id)?.owner===owner));
assert.equal(g.company(owner).economy.money,ownerMoney,'infrastructure owner does not fund player works');
assert.equal(paid-g.economy.money,quote.cost,'player pays the quoted cost');
assert.equal(JSON.stringify(serialize(deserialize(serialize(g)))),JSON.stringify(serialize(g)));
quote=planRelevel(g,tracks,'underground',0);assert(quote.ok,quote.error);
const before=g.economy.money;
g.setAccessPolicy(owner,'auto-reject');
assert(commitRelevel(g,quote),'revoked access rejects a previously approved quote');
assert.equal(g.economy.money,before);assert.equal(st.rail.level,'elevated');
assert(!planRelevel(g,tracks,'underground',0).ok);
g.setAccessPolicy(owner,'open');
quote=planRelevel(g,tracks,'underground',0);assert(quote.ok,quote.error);
g.world.heightsVersion++;
assert.equal(commitRelevel(g,quote),'The track or ground changed, plan again');assert.equal(g.economy.money,before);
quote=planRelevel(g,tracks,'underground',0);assert(quote.ok,quote.error);assert.equal(commitRelevel(g,quote),null);
assert.equal(st.rail.level,'underground');assert.equal(st.owner,owner);
const playerStation=station(g,48,48,Math.PI/2,12,2)!;
assert(playerStation?.rail);assert(!planRelevel(g,playerStation.rail.edges,'elevated',owner).ok,'AI may not alter player infrastructure');
console.log('PASS foreign lift/bury ownership, player-only quoted payment, access revocation, stale terrain and save equality');
